// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZ3FZp79aI6UUt-rN1OJaWSLLnUAK4YM',
    appId: '1:854524006232:web:a9d81f68773a670377df2d',
    messagingSenderId: '854524006232',
    projectId: 'graduation-project-12168',
    authDomain: 'graduation-project-12168.firebaseapp.com',
    storageBucket: 'graduation-project-12168.firebasestorage.app',
    measurementId: 'G-LNB1YJJN8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7hmdHwoCfBTTqB7OfH6fQga-ib3z0cQ',
    appId: '1:854524006232:android:3ac3cca4c5cb6ea577df2d',
    messagingSenderId: '854524006232',
    projectId: 'graduation-project-12168',
    storageBucket: 'graduation-project-12168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-g4UQeUf5cG6qZJQ3B9kuowZZD5z-S6w',
    appId: '1:854524006232:ios:516f4529c4fa66ff77df2d',
    messagingSenderId: '854524006232',
    projectId: 'graduation-project-12168',
    storageBucket: 'graduation-project-12168.firebasestorage.app',
    iosBundleId: 'com.example.graduationproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-g4UQeUf5cG6qZJQ3B9kuowZZD5z-S6w',
    appId: '1:854524006232:ios:60558e45bd4eb0f777df2d',
    messagingSenderId: '854524006232',
    projectId: 'graduation-project-12168',
    storageBucket: 'graduation-project-12168.firebasestorage.app',
    iosBundleId: 'com.example.garduationproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZ3FZp79aI6UUt-rN1OJaWSLLnUAK4YM',
    appId: '1:854524006232:web:156ae59b0bdaee5977df2d',
    messagingSenderId: '854524006232',
    projectId: 'graduation-project-12168',
    authDomain: 'graduation-project-12168.firebaseapp.com',
    storageBucket: 'graduation-project-12168.firebasestorage.app',
    measurementId: 'G-FC4NYE294N',
  );
}
